### ISSUE TITLE
Get error first time i try to logon

### ISSUE THREAD

**Issue by rudvfaden** [sasjs/adapter#741]
First time the page load I get this error

```
core.mjs:6485 
        
       ERROR Error: Uncaught (in promise): r: {"error":{"message":"t.split is not a function","details":{}}}
    at resolvePromise (zone.js:1211:31)
    at resolvePromise (zone.js:1165:17)
    at zone.js:1278:17
    at _ZoneDelegate.invokeTask (zone.js:406:31)
    at Object.onInvokeTask (core.mjs:25535:33)
    at _ZoneDelegate.invokeTask (zone.js:405:60)
    at Zone.runTask (zone.js:178:47)
    at drainMicroTaskQueue (zone.js:585:35)
    at ZoneTask.invokeTask [as invoke] (zone.js:491:21)
    at invokeTask (zone.js:1661:18)
```

After reload everything works.

Is there a way to fix that?

**Comment by allanbowe** [comment]
This issue occurs in the following circumstances:

* SAS 9 Server Type
* SSO
* Redirected Login
* User is NOT authenticated, and so the initial request fails along with a 302 redirect

We should set up a set of mocks to test this particular workflow.
